### ISSUE TITLE
Textos de impacto featured en landing deben tener un máximo de caracteres

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm-content#14]
Para que no suceda esto:

<img width="934" alt="screen shot 2015-10-06 at 2 03 11 pm" src="https://cloud.githubusercontent.com/assets/6226604/10319309/31a8176a-6c33-11e5-9ab1-bec6647197f7.png">

**Comment by carlosmaya** [comment]
@diegobeauroyre podemos cortarlo por un número de palabras especifico, ¿cuántas palabras propones?
