### ISSUE TITLE
Copy de HERRAMIENTAS en landing page

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm-content#2]
![screen shot 2015-09-25 at 6 55 41 pm](https://cloud.githubusercontent.com/assets/2633527/10114498/0c78fff6-63b7-11e5-8bb3-f6f6c3453e3d.png)

**Comment by aniacalderon** [comment]
Interactúa con aplicaciones y visualizaciones para generar nuevo conocimiento.
