### ISSUE TITLE
Actualizar ligas que apunta a old-school ckan

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm-content#22]
https://github.com/mxabierto/dgm-content/search?utf8=%E2%9C%93&q=catalogo.datos.gob.mx

**Comment by carlosmaya** [comment]
creo que no solo es de actualizarlas, hay algunas que ya no existen, o por lo menos no con el mismo nombre

http://busca.datos.gob.mx/#/conjuntos/empresas-productoras-de-minerales-metalicos-y-no-metalicos-embajadas-instituciones-superiores-s
