### ISSUE TITLE
Problema para acceder a los datos y recursos en Salud

### ISSUE THREAD

**Issue by DavidPerales** [mxabierto/dgm-content#37]
Escribo para reportar un error que estoy teniendo que no termino de saber si es culpa mía o de la web. Estoy tratando de descargar los recursos en salud desde la url: http://busca.datos.gob.mx/#/conjuntos/recursos-en-salud
 Siempre me aparece un error que pone "Esta página web no está disponible" ERR_NAME_NOT_RESOLVED En detalles me dice que es un error en la búsqueda de DNS. 
Agradecería que alguien me ayudara para conseguir esos datos ya que los necesito tratar para realizar un estudio más en profundidad. 
Muchas gracias

**Comment by carlosmaya** [comment]
@DavidPerales muchas gracias por reportarlo, ya estamos contactando al Administrador de los Datos para darle solución.

**Comment by DavidPerales** [comment]
Sigo teniendo el mismo problema para descargar los datos. No hay ninguna otra manera de acceder a ellos? :(

**Comment by carlosmaya** [comment]
Que tal @DavidPerales , para comentarte que ya se solucionó el problema, ¿podrías verificar de nuevo? de antemano una disculpa por el tiempo que nos tomo.
