### ISSUE TITLE
Nuevo texto para sección Acerca

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm-content#4]

**Comment by aniacalderon** [comment]
**Acerca de datos.gob.mx**

Esta plataforma es el sitio oficial de Datos Abiertos del Gobierno de la República. Los datos e información en datos.gob.mx son tus datos. 

Datos Abiertos son aquellos datos digitales con las características técnicas y legales necesarias para que cualquiera, en cualquier lugar y momento, los pueda usar, reusar y distribuir libremente. 

Además, datos.gob.mx está disponible en código abierto un repositorio público.

**Datos, Herramientas e Impacto**

Aquí, podrás consultar y descargar en formato libre todos los [Datos](http://busca.datos.gob.mx/#/conjuntos) abiertos del Gobierno de la República, así como de estados, municipios y órganos autónomos que han decidido sumarse para incrementar el beneficio de abrir información pública para la ciudadanía.

En [Herramientas](http://datos.gob.mx/herramientas/)  podrás acceder a una serie de recursos interactivos, mapas y aplicaciones web y móviles que facilitan el uso, visualización y generación de nuevo conocimiento posible gracias a datos abiertos. 

Visita la sección de [Impacto](http://datos.gob.mx/historias/) para conocer las noticias, eventos y casos de uso de Datos Abiertos y entender cómo están ayudando a generar valor en México y el mundo.

**¡Participa!**

Los datos abiertos permiten que los gobiernos, ciudadanos, las organizaciones de sociedad civil y el sector privado, tomen decisiones mejor informadas. El acceso oportuno a los datos ayuda a individuos y organizaciones a desarrollar nuevos conocimientos e ideas innovadoras que pueden generar beneficios sociales y valor económico, para el bienestar de las personas.

La iniciativa de Datos Abiertos es parte de un movimiento global que va más allá de la transparencia y rendición de cuentas, promoviendo el uso de información pública para mejorar el diseño de políticas públicas, y fortalecer los espacios de debate y participación ciudadana.

**Comment by carlosmaya** [comment]
closed by mxabierto/dgm#369
